### ISSUE TITLE
`nhost upgrade` uninstalls nhost

### ISSUE THREAD

**Issue by elitan** [nhost/cli-go#17]
```
╭─eli@Johans-MacBook-Pro.local ~/code/nhost/console-next  ‹main›
╰─➤  sudo nhost upgrade
Password:
[INFO] [v1.0-internal-20] You have the latest version. Hurray!
╭─eli@Johans-MacBook-Pro.local ~/code/nhost/console-next  ‹main›
╰─➤  nhost -d
zsh: command not found: nhost
```

It might have been that I was already on v20 when I ran `nhost upgrade`. I'm not sure.

**Comment by mrinalwahal** [comment]
This isn't a CLI problem. I think it happened because I mistakenly created multiple GH releases on same git tag. IDK why but GH deleted all releases.

As Einstein said, it was spooky action at a distance!

I upgrade to v22, then to v23. And I didn't get this problem.

I'm closing this issue. Feel free to open it if you encounter it again!

**Comment by elitan** [comment]
🧑‍🔬
