### ISSUE TITLE
AUTH_SMTP_HOST

### ISSUE THREAD

**Issue by elitan** [nhost/cli-go#4]
How can `AUTH_SMTP_HOST=nhost_mailhog` be even if `smtp_host: mailhog` is specificed in the `config.yaml` file?

**Comment by mrinalwahal** [comment]
I thought this was required to make the auth container talk to mailhog container. Which it wasn't able to do earlier when we tried to send signin/singup requests.

It did start working once I switched SMTP HOST to `nhost_mailhog`.

Logic: Because container is named `nhost_mailhog` and not `mailhog`.

Want me to look more into it?

**Comment by mrinalwahal** [comment]
I'm closing this issue.
